name: Android-Cloud
on: workflow_dispatch

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install and Start Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled &
          sleep 10
          sudo tailscale up --authkey=tskey-auth-km41PegTt411CNTRL-5TW7SxEt4CVdXscc1sesBVULDisv7VEpP --accept-routes

      - name: Run Android Container
        run: |
          docker run -d \
            --name android-container \
            --privileged \
            --network host \
            -e EMULATOR_DEVICE="Samsung Galaxy S10" \
            -e WEB_VNC=true \
            budtmo/docker-android:emulator_9.0

      - name: Keep Alive
        run: sleep 21600
        run: sleep 21600
